// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7HjrwH2a4FLQz9Z-w_1Q_u1hINwR4bR0',
    appId: '1:76909173406:web:405d9e5443dc8318eb798f',
    messagingSenderId: '76909173406',
    projectId: 'plantsnap-74871',
    authDomain: 'plantsnap-74871.firebaseapp.com',
    storageBucket: 'plantsnap-74871.firebasestorage.app',
    measurementId: 'G-THZECW0XXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEU4y3_7LzyjkV8OIBKxyYvXr49GZjPE',
    appId: '1:76909173406:android:444aa7f6e081563feb798f',
    messagingSenderId: '76909173406',
    projectId: 'plantsnap-74871',
    storageBucket: 'plantsnap-74871.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIPWdzV6FAUcTQbf-UfMOOf3hihdqbww',
    appId: '1:76909173406:ios:5ca02abfc9fd81feeb798f',
    messagingSenderId: '76909173406',
    projectId: 'plantsnap-74871',
    storageBucket: 'plantsnap-74871.firebasestorage.app',
    iosBundleId: 'com.example.plantsnap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIIPWdzV6FAUcTQbf-UfMOOf3hihdqbww',
    appId: '1:76909173406:ios:5ca02abfc9fd81feeb798f',
    messagingSenderId: '76909173406',
    projectId: 'plantsnap-74871',
    storageBucket: 'plantsnap-74871.firebasestorage.app',
    iosBundleId: 'com.example.plantsnap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7HjrwH2a4FLQz9Z-w_1Q_u1hINwR4bR0',
    appId: '1:76909173406:web:2488701f0bd4b7c5eb798f',
    messagingSenderId: '76909173406',
    projectId: 'plantsnap-74871',
    authDomain: 'plantsnap-74871.firebaseapp.com',
    storageBucket: 'plantsnap-74871.firebasestorage.app',
    measurementId: 'G-Z4N2M30Q5P',
  );
}
